---
title: "Covid-19 High Frequency Data"
date: '2020-03-23'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE,
	fig.width = 8,
	cache=TRUE
)
library(tidyverse)
library(lubridate)
library(opendatatoronto)
library(janitor)
library(jsonlite)
library(RSocrata)
library(scales)

```


## Surrey Traffic

```{r}
# Load three weeks of Surrey traffic data (takes a long ass time)

# surrey_traffic_w1 <- fromJSON("http://gis.surrey.ca:8080/fmedatastreaming/TrafficLoopCount/TrafficLoopCounts.fmw?startdatetime=2020-03-01T00:00:00&enddatetime=2020-03-07T23:59:59") %>% clean_names() %>% mutate(date = as.Date(datetime))
# 
# surrey_traffic_w2 <- fromJSON("http://gis.surrey.ca:8080/fmedatastreaming/TrafficLoopCount/TrafficLoopCounts.fmw?startdatetime=2020-03-08T00:00:00&enddatetime=2020-03-14T23:59:59") %>% clean_names() %>% mutate(date = as.Date(datetime))
# 
# surrey_traffic_w3 <- fromJSON("http://gis.surrey.ca:8080/fmedatastreaming/TrafficLoopCount/TrafficLoopCounts.fmw?startdatetime=2020-03-15T00:00:00&enddatetime=2020-03-21T23:59:59") %>% clean_names() %>% mutate(date = as.Date(datetime))
# 
 surrey_traffic_w4 <- fromJSON("http://gis.surrey.ca:8080/fmedatastreaming/TrafficLoopCount/TrafficLoopCounts.fmw?startdatetime=2020-03-22T00:00:00&enddatetime=2020-03-28T23:59:59") %>% clean_names() %>% mutate(date = as.Date(datetime))

surrey_traffic_w4 <- surrey_traffic_w4 %>% select(date, traffic_count)
surrey_traffic <- surrey_traffic %>% select(date, traffic_count)

surrey_traffic <- bind_rows(surrey_traffic, surrey_traffic_w4)

#write_csv(surrey_traffic, "surrey_traffic_march.csv")

#surrey_traffic <- read_csv("surrey_traffic_march.csv")

surrey_traffic_filter <- surrey_traffic %>%
  group_by(date) %>%
  summarise(traffic = sum(traffic_count))



```



```{r}

# Plot Surrey traffic data
ggplot(surrey_traffic_filter, aes(x = date, y = traffic)) +
  geom_point() +
  geom_smooth(method = "loess", se = F) +
  #xlim(min(surrey_traffic_filter$date),max(surrey_traffic_filter$date)+1)
    theme(panel.grid = element_blank(),
      # axis.title.x = element_blank(),
      # axis.text.x = element_blank(),
      # axis.text.y = element_blank(),
      axis.ticks = element_blank(),
      axis.line = element_blank(),
      #legend.position = "bottom",
      panel.background = element_blank(),
      plot.margin = margin(0.5, 0.5, 0.5, 1, "cm"),
      panel.grid.major = element_line(colour = 'transparent')) +
  scale_y_continuous(labels = comma) +
  labs(x = "Date", y = "Daily traffic loop counts", title = "Surrey Traffic Loop Counts in March 2020",
       caption = "Data Source: Surrey Open Data")
       
```


## Toronto shelter

```{r}
# Load Toronto data through opendatatoronto package

packages <- list_packages()

shelter_packages <- search_packages("daily shelter")

shelter_resources <- shelter_packages %>% list_package_resources() %>% 
  filter(id == "524acc3c-3079-4453-a43e-751b996d113c")

shelter_data <- shelter_resources %>% get_resource() %>% clean_names()

toronto_shelter_filter <- shelter_data %>%
  group_by(occupancy_date) %>%
  summarise(occupancy_rate = sum(occupancy)/sum(capacity)) 

```

```{r}

# Plot Tornoto shelter data
ggplot(toronto_shelter_filter, aes(x = occupancy_date, y = occupancy_rate)) +
  geom_point() +
  geom_smooth(method = "loess", se = F) + 
    theme(panel.grid = element_blank(),
      # axis.title.x = element_blank(),
      # axis.text.x = element_blank(),
      # axis.text.y = element_blank(),
      axis.ticks = element_blank(),
      axis.line = element_blank(),
      #legend.position = "bottom",
      panel.background = element_blank(),
      plot.margin = margin(0.5, 0.5, 0.5, 1, "cm"),
      panel.grid.major = element_line(colour = 'transparent')) +
  scale_y_continuous(labels = percent) +
  labs(x = "Date", y = "Daily Occupancy Rate (%)", title = "Toronto Shelter Occupancy in March 2020", 
       caption = "Data Source: Toronto Open Data")
       

```

## Waterloo eco-counter

```{r}
# Load Waterloo data

#waterloo_eco <- fromJSON("https://opendata.arcgis.com/datasets/5d41afff252e45b5b5fe7fc3fd5df3ab_0.geojson")

waterloo_eco <- read_csv("https://opendata.arcgis.com/datasets/5d41afff252e45b5b5fe7fc3fd5df3ab_0.csv")

waterloo_eco_filter <- waterloo_eco %>% 
  clean_names() %>%
  mutate(date = ymd_hms(date)) %>%
  mutate(date_new = as.Date(date), time = format(date, "%H:%M:%S"))

waterloo_group <-waterloo_eco_filter %>%
  group_by(date_new) %>%
  summarise(count = sum(total_count)) %>%
  filter(date_new >= max(date_new) - years(2)) %>%
  filter(!(abs(count - median(count)) > 2*sd(count)))
  


```

```{r}

# Plot Waterloo eco counter data
ggplot(waterloo_group, aes(x = date_new, y = count)) +
  geom_point() +
  geom_smooth(method = "loess", se = F) + 
    theme(panel.grid = element_blank(),
      # axis.title.x = element_blank(),
      # axis.text.x = element_blank(),
      # axis.text.y = element_blank(),
      axis.ticks = element_blank(),
      axis.line = element_blank(),
      #legend.position = "bottom",
      panel.background = element_blank(),
      plot.margin = margin(0.5, 0.5, 0.5, 1, "cm"),
      panel.grid.major = element_line(colour = 'transparent')) +
  scale_x_date(breaks = "16 week") +
  scale_y_continuous(labels = comma) +
  labs(x = "Date", y = "Daily Bike and Pedestrian Count", title = "Waterloo Eco Counter Data since December 2020", 
       caption = "Data Source: Waterloo Open Data")
       

```

```{r}
# Load Edmonton data

edmonton_test <- read.socrata("https://data.edmonton.ca/resource/tq23-qn4m.json?$where=log_timstamp between '2020-03-01T00:00:00.000' and '2020-05-05T23:59:59.000'")

# edmonton_eco <- read.socrata("https://data.edmonton.ca/resource/tq23-qn4m.csv") # reads whole damn dataset

edmonton_filter <- edmonton_test %>%  
  clean_names() %>%
  mutate(log_timstamp = ymd_hms(log_timstamp)) %>%
  mutate(date = as.Date(log_timstamp), time = format(log_timstamp, "%H:%M:%S")) %>%
  mutate(combined_total_count = as.numeric(combined_total_count))

edmonton_group <-edmonton_filter %>%
  group_by(date) %>%
  summarise(count = sum(combined_total_count)) #%>%
  #filter(date_new >= max(date_new) - years(1)) %>%
  #filter(!(abs(count - median(count)) > 2*sd(count)))
  
```

```{r}

# Plot Edmonton eco counter data
ggplot(edmonton_group %>% filter(date >= "2020-03-01"), aes(x = date, y = count)) +
  geom_point() +
  geom_smooth(method = "loess", se = F) + 
    theme(panel.grid = element_blank(),
      # axis.title.x = element_blank(),
      # axis.text.x = element_blank(),
      # axis.text.y = element_blank(),
      axis.ticks = element_blank(),
      axis.line = element_blank(),
      #legend.position = "bottom",
      panel.background = element_blank(),
      plot.margin = margin(0.5, 0.5, 0.5, 1, "cm"),
      panel.grid.major = element_line(colour = 'transparent')) +
  scale_y_continuous(labels = comma) +
  labs(x = "Date", y = "Daily Bike and Pedestrian Count", title = "Edmonton Eco Counter Data for March 2020", 
       caption = "Data Source: Edmonton Open Data")
       

```

## Construct a social interaction index (i.e. inverse of social isolation)
```{r}

# Establish car baseline (first week of March) using Surrey data

car_baseline <- surrey_traffic_filter %>%
  filter(date < "2020-03-08") %>%
  mutate(week = "One") %>%
  group_by(week) %>%
  summarise(average = mean(traffic)) %>%
  pull(average)
  
  

# Establish pedestrian and bicycle baseline (first week of March) using Edmonton data

ped_baseline <- edmonton_group %>%
  filter(date < "2020-03-08") %>%
  filter(date > "2020-03-01") %>% # filtering out first of March because it seems like a weird outlier
  mutate(week = "One") %>%
  group_by(week) %>%
  summarise(average = mean(count)) %>%
  pull(average)

# Create car index

car_index <- surrey_traffic_filter %>%
  mutate(baseline = car_baseline) %>%
  mutate(index_car = (traffic/baseline*100)) %>%
  select(-traffic, -baseline)

# Create ped/bike index

ped_index <- edmonton_group %>%
  mutate(baseline = ped_baseline) %>%
  mutate(index_ped = (count/baseline*100)) %>%
  select(-count, -baseline)

# Create combined, "Social Interaction Index" (SII) where both car and ped indices have equal weights

sii <- left_join(car_index, ped_index, by = "date") %>%
  mutate(index = rowMeans(select(., starts_with("index")), na.rm = TRUE)) %>%
  filter(date > "2020-03-01") #excluding first day of March due to data error caused outlier
  

```

```{r}

# Plot social interaction index
ggplot(sii, aes(x = date, y = index)) +
  geom_point() +
  annotate("rect", fill = "grey", alpha = 0.4, 
        xmin = as.Date("2020-03-13"), xmax = as.Date("2020-03-14"),
        ymin = -Inf, ymax = Inf) +
    # annotate("text", 
    #     x = as.Date("2020-03-15"), y = 110,
    #     label = "March 13: returning international travellers advised to self-isolate for 14 days.") +
  geom_vline(aes(xintercept = as.numeric(as.POSIXct(as.Date("2020-03-13")))), colour = "red") +
  geom_hline(yintercept = 100) +
  geom_smooth(method = "loess", se = F) + 
    theme(panel.grid = element_blank(),
      # axis.title.x = element_blank(),
      # axis.text.x = element_blank(),
      # axis.text.y = element_blank(),
      axis.ticks = element_blank(),
      axis.line = element_blank(),
      #legend.position = "bottom",
      panel.background = element_blank(),
      #plot.margin = margin(0.5, 0.5, 0.5, 1, "cm"),
      panel.grid.major = element_line(colour = 'transparent')) +
  scale_y_continuous(labels = comma, position = "right") +
  labs(x = "Date", y = "Index", title = "Social Interaction Index", 
       subtitle = "Baseline is the average daily car, pedestrian, and bicycle traffic count for the first week of March",
       caption = "Data Sources: Edmonton Open Data and Surrey Open Data\nShaded date (Mar. 13) represents when returning international travellers were advised to self-isolate for 14 days")
       
```

